apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.image.defaultPort }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Chart.Name }}
